s = (input("enter the your name : "))
a = input("enter the string2 : ")
l = len(s)
print(s)
print("hello " + s)
print(s * 2)
print(s[1:l-1])
print(s==a)
print(s!=a)
print(a in s)
print(a not in s)
print(' hey %s' % (s))